
spring:
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    cache: false
    suffix: .html
    encoding: UTF-8
    mode: HTML5
#这是数据库的依赖
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rescue?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    password: 1234
    username: root
  redis: # redis配置
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8
  mail:
    host: smtp.qq.com
    port: 465
    username: 1807367347@qq.com
    password: xrcozyawmyzqegci
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true


# 阿里云短信配置
aliyun:
  sms:
    access-key-id: LTAI5tPRQ2mjozsgWb5qpgLZ
    access-key-secret: bJklOOdXvXc2tctX92njTWI8ldTIkJ
    sign-name: 暖心归家
    template-code: SMS_305062994

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.maka.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: info
    com.maka.mapper: debug
    org.mybatis: debug
    org.springframework.jdbc.datasource: debug
server:
  port: 8080
